### ISSUE TITLE
本周收益已达上限无法自动暂停

### ISSUE THREAD

**Issue by besteric** [DaveBoy/kog-money#1]
试了下，图像识别还蛮准确的，比单纯的设定时间延迟精准很多

另外，原版好像有个练英雄熟练度的脚本，能否顺便移植过来

**Comment by DaveBoy** [comment]
我也发现收益上限识别这个问题了，但是我单独测试的时候又tm是准的。。。我放家里的时候又不准。。
我有空再试试，你如果遇到这种情况能复现的话最好提供一下screen.png

**Comment by DaveBoy** [comment]
练英雄熟练度那个我是用不到就没移植。。。

**Comment by besteric** [comment]
好的，我这周还没开始刷金币

**Comment by besteric** [comment]
![sc222reen](https://user-images.githubusercontent.com/535385/103139322-dd713000-4715-11eb-808b-185fa3d46923.png)

**Comment by besteric** [comment]
这个图片无法识别

**Comment by DaveBoy** [comment]
收到，我今天在搬电脑，发现电信网线没弄好，明天弄好了看一下

**Comment by DaveBoy** [comment]
> 这个图片无法识别

找到问题了 ，因为1280那个截图是比较久的了，我自己用的2248的分辨率，我重新制作了1280的b_finish截图，具体过程你可以参照根目录下的‘制作截图.gif’

**Comment by DaveBoy** [comment]
1280的缺失截图（参照2248的目录）你可以自己参照gif制作，不制作也问题不大，只是缺少对对应部分的识别判断，如果制作了也可以提交PR
