### ISSUE TITLE
S22 赛季新UI界面，拜托有时间适配下，谢啦

### ISSUE THREAD

**Issue by besteric** [DaveBoy/kog-money#2]
RT

**Comment by DaveBoy** [comment]
收到，最迟本周末

**Comment by ldxm9527** [comment]
我以爲替換了匹配的素材圖片，修改一下點擊坐標就好啦，沒想到還是有bug，看來我對大佬的code理解還是不夠深刻~

**Comment by DaveBoy** [comment]
周末比较忙，现在才更新游戏，具体啥问题我还没看  估计只是 更新一下重新截图裁剪就行了

**Comment by DaveBoy** [comment]
截图已更新，看readme的更新说明。
主要就更新了一个坐标和几个截图，2248分辨率的更新了（剩下金币上限没制作），其他分辨率需要自己制作。

@besteric @ldxm9527

**Comment by besteric** [comment]
好的，收到，我晚上回家测试下

**Comment by DaveBoy** [comment]
我的微信区金币上限图片依旧可以匹配，看来可以不改上限那张图。

**Comment by besteric** [comment]
<img width="100" alt="b_finish" src="https://user-images.githubusercontent.com/535385/106089080-2deb0b80-6162-11eb-96aa-58a042173780.png">

**Comment by besteric** [comment]
我试过你的 2248*1080 分辨率的图片，默认的无法识别，重新截图了可以正常识别，不知道是不是我的个例

**Comment by besteric** [comment]
我是雷电模拟器操作的，难道是因为我 4K 显示器，我的截图比原图更锐利点 Orz

**Comment by DaveBoy** [comment]
不太清楚   你是微信区吗   我之前好像也出现过不能识别的情况，但是没太注意。

**Comment by besteric** [comment]
> 不太清楚 你是微信区吗 我之前好像也出现过不能识别的情况，但是没太注意。

对额，安卓微信区，不知道是不是个例...

**Comment by xieyongshuai** [comment]
坐标匹配后好像没起作用

**Comment by DaveBoy** [comment]
> 对额，安卓微信区，不知道是不是个例...

可能是有些设备匹配度不够高（默认写的0.9），应该还是要重新制作。我周末重新截一下。

**Comment by DaveBoy** [comment]
> 坐标匹配后好像没起作用

什么意思

**Comment by xieyongshuai** [comment]
我第一次直接运行的，他应该是定位的不准吧 然后点到了英雄详情页里去了，然后我又运行test  把代码里的分辨率改了。然后还是点到英雄详情页了

**Comment by DaveBoy** [comment]
> 我第一次直接运行的，他应该是定位的不准吧 然后点到了英雄详情页里去了，然后我又运行test 把代码里的分辨率改了。然后还是点到英雄详情页了

分辨率是自动识别的。。。

识别了之后自动寻找对应的截图文件夹。

至于开始那几个坐标是根据点的坐标和屏幕分辨率进行位置缩放找的。

建议你登录到首页，然后关了所有的弹窗，然后再运行'刷金币.bat'

**Comment by xieyongshuai** [comment]
我的分辨率是(1080, 2220) ，还要重新截图嘛

**Comment by DaveBoy** [comment]
> 我的分辨率是(1080, 2220) ，还要重新截图嘛

分辨率不一样应该要截图，我现在只更新了2248的没有2220的，制作教程见readme。

就算没有截图  应该也能跳转到选择关卡的页面，只是无法继续后面的流程

**Comment by xieyongshuai** [comment]
我这直接跑到吕布详情页了😂

**Comment by DaveBoy** [comment]
这就不太清楚你是哪块出现的问题了。。。

**Comment by DaveBoy** [comment]
已修复问题：vx和qq区相似度不同问题。
解决方法：
1.调低相似度，最新已从0.9下调到0.85，最低建议0.8
2.同一个图可以分别截图。（如b_finish和b_finish_vx）
